POBLACION_SIZE = 500
GENERACIONES = 100
TASA_MUTACION = 0.1
APTITUD = 98

SIZE_OVAL = 40
SIZE_EDGE = 3
SIZE_ARROW =(5, 10, 10)
SIZE_TEXT = 17

COLOR_IN = 'green'
COLOR_OUT = 'blue'
COLOR_NORMAL = 'white'